In [1]:
import pandas as pd
import pickle
import blackjack

In [2]:
# run the Blackjack simulation
deck_count = 2
num_players = 3
num_rounds = 1000
cut_cards = True
dealer_hit_to = 17
hit_strategies = {0: {2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: 17, 9: 17, 10: 17, 11: 17},
				  1: {2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: 17, 9: 17, 10: 17, 11: 17},
				  2: {2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: 17, 9: 17, 10: 17, 11: 17}}

blackjack.game(deck_count, num_players, num_rounds, cut_cards, dealer_hit_to, hit_strategies)

Done!

In [3]:
# import the pickled dataframe
infile = open('blackjack.pickle','rb')
df = pickle.load(infile)
infile.close()

In [4]:
df.head(20)

,name,total,result,bust,blackjack,cards,hit_strategy,dealer_up_card,hand_split,round,hand
0,Player1,15,win,False,False,"[8, 7]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",5,False,0,0
1,Player2,12,win,False,False,"[4, 8]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",5,False,0,0
2,Player3,13,win,False,False,"[3, Q]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",5,False,0,0
3,dealer,26,None,True,False,"[5, 4, 4, 2, A, Q]",17,5,False,0,0
4,Player1,20,win,False,False,"[9, A]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",4,False,1,0
5,Player2,14,win,False,False,"[A, 3]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",4,False,1,0
6,Player3,14,win,False,False,"[8, 6]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",4,False,1,0
7,dealer,26,None,True,False,"[4, A, 8, A, 2, K]",17,4,False,1,0
8,Player1,18,lose,False,False,"[6, 6, 6]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",10,False,2,0
9,Player2,19,lose,False,False,"[J, 9]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",10,False,2,0
10,Player3,20,lose,False,False,"[3, 7, J]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",10,False,2,0
11,dealer,21,None,False,False,"[K, 3, 8]",17,10,False,2,0
12,Player1,17,push,False,False,"[9, 3, 5]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",10,False,3,0
13,Player2,17,push,False,False,"[2, J, 5]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",10,False,3,0
14,Player3,17,push,False,False,"[5, 2, 10]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",10,False,3,0
15,dealer,17,None,False,False,"[K, 7]",17,10,False,3,0
16,Player1,19,win,False,False,"[A, 8]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",6,True,4,0
17,Player1,20,win,False,False,"[A, 9]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",6,True,4,1
18,Player2,13,lose,False,False,"[7, 6]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",6,False,4,0
19,Player3,19,win,False,False,"[Q, 9]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",6,False,4,0

In [5]:
df['dealer_up_card'].value_counts()

10    1257
2      350
4      342
9      339
6      313
8      306
5      306
11     302
7      287
3      277
Name: dealer_up_card, dtype: int64

In [7]:
for p in df['name'].unique():
    if p != 'dealer':
        print(p)
        print(df[df['name'] == p]['result'].value_counts())
        print('______')

Player1
lose    498
win     432
push     95
Name: result, dtype: int64
______
Player2
lose    492
win     442
push     98
Name: result, dtype: int64
______
Player3
lose    491
win     436
push     95
Name: result, dtype: int64
______

In [7]:
df[df['hand_split'] == True]

,name,total,result,bust,blackjack,cards,hit_strategy,dealer_up_card,hand_split,round,hand
86,Player3,18,win,False,False,"[8, 2, 2, 3, 3]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",11,True,21,0
87,Player3,19,win,False,False,"[8, A]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",11,True,21,1
91,Player3,15,lose,False,False,"[2, K, 3]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",3,True,22,0
92,Player3,15,lose,False,False,"[2, 7, 6]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",3,True,22,1
188,Player3,17,lose,False,False,"[8, 9]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",10,True,46,0
...,...,...,...,...,...,...,...,...,...,...,...
3981,Player1,19,push,False,False,"[9, 2, 8]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",9,True,973,1
4022,Player2,21,win,False,False,"[A, Q]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",2,True,983,0
4023,Player2,16,win,False,False,"[A, 5]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",2,True,983,1
4072,Player3,20,win,False,False,"[9, A]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",10,True,995,0
4073,Player3,20,win,False,False,"[9, A]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",10,True,995,1

In [8]:
df[df['round'] == 21]

,name,total,result,bust,blackjack,cards,hit_strategy,dealer_up_card,hand_split,round,hand
84,Player1,24,lose,True,False,"[2, 9, 3, J]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",11,False,21,0
85,Player2,20,win,False,False,"[4, J, 6]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",11,False,21,0
86,Player3,18,win,False,False,"[8, 2, 2, 3, 3]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",11,True,21,0
87,Player3,19,win,False,False,"[8, A]","{2: 13, 3: 13, 4: 12, 5: 12, 6: 12, 7: 12, 8: ...",11,True,21,1
88,dealer,17,None,False,False,"[A, 6]",17,11,False,21,0